#nullable enable
namespace TH5D;

partial class fmHoSoSinhVien
{
    private System.ComponentModel.IContainer? components;
    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        AutoScaleMode = AutoScaleMode.Dpi;
        Font = new Font("Tahoma", 11F);
        grpThongTin = new GroupBox();
        lblName = new Label();
        textBoxName = new TextBox();
        lblId = new Label();
        textBoxId = new TextBox();
        lblSex = new Label();
        grpGioiTinh = new GroupBox();
        radioButtonMale = new RadioButton();
        radioButtonFemale = new RadioButton();
        lblForeign = new Label();
        checkBoxEng = new CheckBox();
        checkBoxFra = new CheckBox();
        checkBoxChi = new CheckBox();
        lblEth = new Label();
        comboBoxEth = new ComboBox();
        lstv1 = new ListView();
        btnAdd = new Button();
        btnEdit = new Button();
        btnDelete = new Button();
        grpThongTin.SuspendLayout();
        grpGioiTinh.SuspendLayout();
        SuspendLayout();
        grpThongTin.Name = "grpThongTin";
        grpThongTin.Location = new Point(20, 15);
        grpThongTin.Size = new Size(860, 280);
        grpThongTin.TabIndex = 0;
        grpThongTin.Text = "Thông tin sinh viên";
        lblName.Name = "lblName";
        lblName.Location = new Point(20, 35);
        lblName.Size = new Size(160, 28);
        lblName.TabIndex = 1;
        lblName.Text = "Họ và tên";
        lblName.AutoSize = false;
        lblName.TextAlign = ContentAlignment.MiddleLeft;
        textBoxName.Name = "textBoxName";
        textBoxName.Location = new Point(190, 33);
        textBoxName.Size = new Size(630, 28);
        textBoxName.TabIndex = 2;
        textBoxName.MaxLength = 100;
        lblId.Name = "lblId";
        lblId.Location = new Point(20, 85);
        lblId.Size = new Size(160, 28);
        lblId.TabIndex = 3;
        lblId.Text = "Mã sinh viên";
        lblId.AutoSize = false;
        lblId.TextAlign = ContentAlignment.MiddleLeft;
        textBoxId.Name = "textBoxId";
        textBoxId.Location = new Point(190, 83);
        textBoxId.Size = new Size(630, 28);
        textBoxId.TabIndex = 4;
        textBoxId.MaxLength = 20;
        lblSex.Name = "lblSex";
        lblSex.Location = new Point(20, 137);
        lblSex.Size = new Size(160, 28);
        lblSex.TabIndex = 5;
        lblSex.Text = "Giới tính";
        lblSex.AutoSize = false;
        lblSex.TextAlign = ContentAlignment.MiddleLeft;
        grpGioiTinh.Name = "grpGioiTinh";
        grpGioiTinh.Location = new Point(185, 120);
        grpGioiTinh.Size = new Size(635, 55);
        grpGioiTinh.TabIndex = 6;
        grpGioiTinh.Text = "";
        radioButtonMale.Name = "radioButtonMale";
        radioButtonMale.Location = new Point(10, 18);
        radioButtonMale.Size = new Size(130, 28);
        radioButtonMale.TabIndex = 7;
        radioButtonMale.Text = "Nam";
        radioButtonMale.Checked = true;
        radioButtonFemale.Name = "radioButtonFemale";
        radioButtonFemale.Location = new Point(160, 18);
        radioButtonFemale.Size = new Size(130, 28);
        radioButtonFemale.TabIndex = 8;
        radioButtonFemale.Text = "Nữ";
        lblForeign.Name = "lblForeign";
        lblForeign.Location = new Point(20, 190);
        lblForeign.Size = new Size(160, 28);
        lblForeign.TabIndex = 9;
        lblForeign.Text = "Ngoại ngữ";
        lblForeign.AutoSize = false;
        lblForeign.TextAlign = ContentAlignment.MiddleLeft;
        checkBoxEng.Name = "checkBoxEng";
        checkBoxEng.Location = new Point(190, 190);
        checkBoxEng.Size = new Size(130, 28);
        checkBoxEng.TabIndex = 10;
        checkBoxEng.Text = "Anh";
        checkBoxFra.Name = "checkBoxFra";
        checkBoxFra.Location = new Point(350, 190);
        checkBoxFra.Size = new Size(130, 28);
        checkBoxFra.TabIndex = 11;
        checkBoxFra.Text = "Pháp";
        checkBoxChi.Name = "checkBoxChi";
        checkBoxChi.Location = new Point(510, 190);
        checkBoxChi.Size = new Size(130, 28);
        checkBoxChi.TabIndex = 12;
        checkBoxChi.Text = "Hoa";
        lblEth.Name = "lblEth";
        lblEth.Location = new Point(20, 235);
        lblEth.Size = new Size(160, 28);
        lblEth.TabIndex = 13;
        lblEth.Text = "Dân tộc";
        lblEth.AutoSize = false;
        lblEth.TextAlign = ContentAlignment.MiddleLeft;
        comboBoxEth.Name = "comboBoxEth";
        comboBoxEth.Location = new Point(190, 233);
        comboBoxEth.Size = new Size(630, 28);
        comboBoxEth.TabIndex = 14;
        comboBoxEth.DropDownStyle = ComboBoxStyle.DropDownList;
        lstv1.Name = "lstv1";
        lstv1.Location = new Point(20, 310);
        lstv1.Size = new Size(860, 230);
        lstv1.TabIndex = 15;
        lstv1.View = View.Details;
        lstv1.FullRowSelect = true;
        lstv1.GridLines = true;
        lstv1.MultiSelect = false;
        lstv1.HideSelection = false;
        lstv1.Columns.Add(new ColumnHeader { Name = "col0", Text = "Họ và tên", Width = 250 });
        lstv1.Columns.Add(new ColumnHeader { Name = "col1", Text = "Mã sinh viên", Width = 160 });
        lstv1.Columns.Add(new ColumnHeader { Name = "col2", Text = "Giới tính", Width = 110 });
        lstv1.Columns.Add(new ColumnHeader { Name = "col3", Text = "Ngoại ngữ", Width = 175 });
        lstv1.Columns.Add(new ColumnHeader { Name = "col4", Text = "Dân tộc", Width = 140 });
        btnAdd.Name = "btnAdd";
        btnAdd.Location = new Point(220, 560);
        btnAdd.Size = new Size(140, 36);
        btnAdd.TabIndex = 16;
        btnAdd.Text = "Thêm";
        btnAdd.UseVisualStyleBackColor = true;
        btnEdit.Name = "btnEdit";
        btnEdit.Location = new Point(380, 560);
        btnEdit.Size = new Size(140, 36);
        btnEdit.TabIndex = 17;
        btnEdit.Text = "Sửa";
        btnEdit.UseVisualStyleBackColor = true;
        btnDelete.Name = "btnDelete";
        btnDelete.Location = new Point(540, 560);
        btnDelete.Size = new Size(140, 36);
        btnDelete.TabIndex = 18;
        btnDelete.Text = "Xóa";
        btnDelete.UseVisualStyleBackColor = true;
        contextMenuStrip1 = new ContextMenuStrip(components);
        deleteToolStripMenuItem = new ToolStripMenuItem("Xóa") { Name = "deleteToolStripMenuItem" };
        contextMenuStrip1.Items.Add(deleteToolStripMenuItem);
        lstv1.ContextMenuStrip = contextMenuStrip1;
        Controls.Add(btnDelete);
        Controls.Add(btnEdit);
        Controls.Add(btnAdd);
        Controls.Add(lstv1);
        grpThongTin.Controls.Add(comboBoxEth);
        grpThongTin.Controls.Add(lblEth);
        grpThongTin.Controls.Add(checkBoxChi);
        grpThongTin.Controls.Add(checkBoxFra);
        grpThongTin.Controls.Add(checkBoxEng);
        grpThongTin.Controls.Add(lblForeign);
        grpGioiTinh.Controls.Add(radioButtonFemale);
        grpGioiTinh.Controls.Add(radioButtonMale);
        grpThongTin.Controls.Add(grpGioiTinh);
        grpThongTin.Controls.Add(lblSex);
        grpThongTin.Controls.Add(textBoxId);
        grpThongTin.Controls.Add(lblId);
        grpThongTin.Controls.Add(textBoxName);
        grpThongTin.Controls.Add(lblName);
        Controls.Add(grpThongTin);
        ClientSize = new Size(900, 620);
        AutoScaleDimensions = new SizeF(96F, 96F);
        Name = "fmHoSoSinhVien";
        Text = "TH5D - Tại lớp 1 - Hồ sơ sinh viên";
        StartPosition = FormStartPosition.CenterParent;
        FormBorderStyle = FormBorderStyle.FixedDialog;
        MaximizeBox = false;
        grpGioiTinh.ResumeLayout(false);
        grpGioiTinh.PerformLayout();
        grpThongTin.ResumeLayout(false);
        grpThongTin.PerformLayout();
        ResumeLayout(false);
        PerformLayout();
    }

    private GroupBox grpThongTin = null!;
    private Label lblName = null!;
    private TextBox textBoxName = null!;
    private Label lblId = null!;
    private TextBox textBoxId = null!;
    private Label lblSex = null!;
    private GroupBox grpGioiTinh = null!;
    private RadioButton radioButtonMale = null!;
    private RadioButton radioButtonFemale = null!;
    private Label lblForeign = null!;
    private CheckBox checkBoxEng = null!;
    private CheckBox checkBoxFra = null!;
    private CheckBox checkBoxChi = null!;
    private Label lblEth = null!;
    private ComboBox comboBoxEth = null!;
    private ListView lstv1 = null!;
    private Button btnAdd = null!;
    private Button btnEdit = null!;
    private Button btnDelete = null!;
    private ContextMenuStrip contextMenuStrip1 = null!;
    private ToolStripMenuItem deleteToolStripMenuItem = null!;
}
