#nullable enable
namespace TH5D;

partial class fmSinhVienSql
{
    private System.ComponentModel.IContainer? components;
    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        AutoScaleMode = AutoScaleMode.Dpi;
        Font = new Font("Tahoma", 11F);
        grpNhap = new GroupBox();
        lblMaSinhVien = new Label();
        txtMaSinhVien = new TextBox();
        lblMaLop = new Label();
        txtMaLop = new TextBox();
        lblHoTen = new Label();
        txtHoTen = new TextBox();
        lblNgaySinh = new Label();
        dtpNgaySinh = new DateTimePicker();
        btnThem = new Button();
        btnSua = new Button();
        btnXoa = new Button();
        lblHuongDan = new Label();
        grpNhap.SuspendLayout();
        SuspendLayout();
        grpNhap.Name = "grpNhap";
        grpNhap.Location = new Point(20, 15);
        grpNhap.Size = new Size(640, 253);
        grpNhap.TabIndex = 0;
        grpNhap.Text = "Thông tin";
        lblMaSinhVien.Name = "lblMaSinhVien";
        lblMaSinhVien.Location = new Point(20, 35);
        lblMaSinhVien.Size = new Size(145, 28);
        lblMaSinhVien.TabIndex = 1;
        lblMaSinhVien.Text = "Mã sinh viên";
        lblMaSinhVien.AutoSize = false;
        lblMaSinhVien.TextAlign = ContentAlignment.MiddleLeft;
        txtMaSinhVien.Name = "txtMaSinhVien";
        txtMaSinhVien.Location = new Point(180, 33);
        txtMaSinhVien.Size = new Size(430, 28);
        txtMaSinhVien.TabIndex = 2;
        txtMaSinhVien.MaxLength = 20;
        lblMaLop.Name = "lblMaLop";
        lblMaLop.Location = new Point(20, 87);
        lblMaLop.Size = new Size(145, 28);
        lblMaLop.TabIndex = 3;
        lblMaLop.Text = "Mã lớp";
        lblMaLop.AutoSize = false;
        lblMaLop.TextAlign = ContentAlignment.MiddleLeft;
        txtMaLop.Name = "txtMaLop";
        txtMaLop.Location = new Point(180, 85);
        txtMaLop.Size = new Size(430, 28);
        txtMaLop.TabIndex = 4;
        txtMaLop.MaxLength = 20;
        lblHoTen.Name = "lblHoTen";
        lblHoTen.Location = new Point(20, 139);
        lblHoTen.Size = new Size(145, 28);
        lblHoTen.TabIndex = 5;
        lblHoTen.Text = "Họ tên";
        lblHoTen.AutoSize = false;
        lblHoTen.TextAlign = ContentAlignment.MiddleLeft;
        txtHoTen.Name = "txtHoTen";
        txtHoTen.Location = new Point(180, 137);
        txtHoTen.Size = new Size(430, 28);
        txtHoTen.TabIndex = 6;
        txtHoTen.MaxLength = 100;
        lblNgaySinh.Name = "lblNgaySinh";
        lblNgaySinh.Location = new Point(20, 191);
        lblNgaySinh.Size = new Size(145, 28);
        lblNgaySinh.TabIndex = 7;
        lblNgaySinh.Text = "Ngày sinh";
        lblNgaySinh.AutoSize = false;
        lblNgaySinh.TextAlign = ContentAlignment.MiddleLeft;
        dtpNgaySinh.Name = "dtpNgaySinh";
        dtpNgaySinh.Location = new Point(180, 189);
        dtpNgaySinh.Size = new Size(430, 28);
        dtpNgaySinh.TabIndex = 8;
        dtpNgaySinh.Format = DateTimePickerFormat.Custom;
        dtpNgaySinh.CustomFormat = "dd/MM/yyyy";
        dtpNgaySinh.ShowCheckBox = true;
        dtpNgaySinh.Checked = false;
        btnThem.Name = "btnThem";
        btnThem.Location = new Point(165, 288);
        btnThem.Size = new Size(140, 36);
        btnThem.TabIndex = 9;
        btnThem.Text = "Thêm";
        btnThem.UseVisualStyleBackColor = true;
        btnSua.Name = "btnSua";
        btnSua.Location = new Point(320, 288);
        btnSua.Size = new Size(140, 36);
        btnSua.TabIndex = 10;
        btnSua.Text = "Sửa";
        btnSua.UseVisualStyleBackColor = true;
        btnXoa.Name = "btnXoa";
        btnXoa.Location = new Point(475, 288);
        btnXoa.Size = new Size(140, 36);
        btnXoa.TabIndex = 11;
        btnXoa.Text = "Xóa";
        btnXoa.UseVisualStyleBackColor = true;
        lblHuongDan.Name = "lblHuongDan";
        lblHuongDan.Location = new Point(25, 336);
        lblHuongDan.Size = new Size(630, 38);
        lblHuongDan.TabIndex = 12;
        lblHuongDan.Text = "Xóa: mã sinh viên và họ tên; bỏ chọn ngày sinh, để trống mã lớp.";
        lblHuongDan.AutoSize = false;
        lblHuongDan.TextAlign = ContentAlignment.MiddleLeft;
        Controls.Add(lblHuongDan);
        Controls.Add(btnXoa);
        Controls.Add(btnSua);
        Controls.Add(btnThem);
        grpNhap.Controls.Add(dtpNgaySinh);
        grpNhap.Controls.Add(lblNgaySinh);
        grpNhap.Controls.Add(txtHoTen);
        grpNhap.Controls.Add(lblHoTen);
        grpNhap.Controls.Add(txtMaLop);
        grpNhap.Controls.Add(lblMaLop);
        grpNhap.Controls.Add(txtMaSinhVien);
        grpNhap.Controls.Add(lblMaSinhVien);
        Controls.Add(grpNhap);
        ClientSize = new Size(680, 388);
        AutoScaleDimensions = new SizeF(96F, 96F);
        Name = "fmSinhVienSql";
        Text = "TH5D - SQL - Quản lý sinh viên";
        StartPosition = FormStartPosition.CenterParent;
        FormBorderStyle = FormBorderStyle.FixedDialog;
        MaximizeBox = false;
        grpNhap.ResumeLayout(false);
        grpNhap.PerformLayout();
        ResumeLayout(false);
        PerformLayout();
    }

    private GroupBox grpNhap = null!;
    private Label lblMaSinhVien = null!;
    private TextBox txtMaSinhVien = null!;
    private Label lblMaLop = null!;
    private TextBox txtMaLop = null!;
    private Label lblHoTen = null!;
    private TextBox txtHoTen = null!;
    private Label lblNgaySinh = null!;
    private DateTimePicker dtpNgaySinh = null!;
    private Button btnThem = null!;
    private Button btnSua = null!;
    private Button btnXoa = null!;
    private Label lblHuongDan = null!;
}
