#nullable enable
namespace TH5D;

partial class fmTaiKhoan
{
    private System.ComponentModel.IContainer? components;
    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        AutoScaleMode = AutoScaleMode.Dpi;
        Font = new Font("Tahoma", 11F);
        lblTitle = new Label();
        lblAccount = new Label();
        textBoxAccount = new TextBox();
        lblCustomer = new Label();
        textBoxCustomer = new TextBox();
        lblAddress = new Label();
        textBoxAddress = new TextBox();
        lblAmount = new Label();
        textBoxAmount = new TextBox();
        lblFormat = new Label();
        buttonAdd = new Button();
        buttonSave = new Button();
        buttonDelete = new Button();
        buttonExit = new Button();
        listViewAccounts = new ListView();
        lblTotal = new Label();
        textBoxTotal = new TextBox();
        SuspendLayout();
        lblTitle.Name = "lblTitle";
        lblTitle.Location = new Point(20, 15);
        lblTitle.Size = new Size(900, 38);
        lblTitle.TabIndex = 0;
        lblTitle.Text = "QUẢN LÝ THÔNG TIN TÀI KHOẢN";
        lblTitle.AutoSize = false;
        lblTitle.TextAlign = ContentAlignment.MiddleLeft;
        lblTitle.Font = new Font("Tahoma", 15F, FontStyle.Bold);
        lblTitle.TextAlign = ContentAlignment.MiddleCenter;
        lblAccount.Name = "lblAccount";
        lblAccount.Location = new Point(30, 70);
        lblAccount.Size = new Size(230, 28);
        lblAccount.TabIndex = 1;
        lblAccount.Text = "Số tài khoản";
        lblAccount.AutoSize = false;
        lblAccount.TextAlign = ContentAlignment.MiddleLeft;
        textBoxAccount.Name = "textBoxAccount";
        textBoxAccount.Location = new Point(280, 68);
        textBoxAccount.Size = new Size(625, 28);
        textBoxAccount.TabIndex = 2;
        lblCustomer.Name = "lblCustomer";
        lblCustomer.Location = new Point(30, 118);
        lblCustomer.Size = new Size(230, 28);
        lblCustomer.TabIndex = 3;
        lblCustomer.Text = "Tên khách hàng";
        lblCustomer.AutoSize = false;
        lblCustomer.TextAlign = ContentAlignment.MiddleLeft;
        textBoxCustomer.Name = "textBoxCustomer";
        textBoxCustomer.Location = new Point(280, 116);
        textBoxCustomer.Size = new Size(625, 28);
        textBoxCustomer.TabIndex = 4;
        lblAddress.Name = "lblAddress";
        lblAddress.Location = new Point(30, 166);
        lblAddress.Size = new Size(230, 28);
        lblAddress.TabIndex = 5;
        lblAddress.Text = "Địa chỉ khách hàng";
        lblAddress.AutoSize = false;
        lblAddress.TextAlign = ContentAlignment.MiddleLeft;
        textBoxAddress.Name = "textBoxAddress";
        textBoxAddress.Location = new Point(280, 164);
        textBoxAddress.Size = new Size(625, 28);
        textBoxAddress.TabIndex = 6;
        lblAmount.Name = "lblAmount";
        lblAmount.Location = new Point(30, 214);
        lblAmount.Size = new Size(230, 28);
        lblAmount.TabIndex = 7;
        lblAmount.Text = "Số tiền trong tài khoản";
        lblAmount.AutoSize = false;
        lblAmount.TextAlign = ContentAlignment.MiddleLeft;
        textBoxAmount.Name = "textBoxAmount";
        textBoxAmount.Location = new Point(280, 212);
        textBoxAmount.Size = new Size(625, 28);
        textBoxAmount.TabIndex = 8;
        lblFormat.Name = "lblFormat";
        lblFormat.Location = new Point(280, 258);
        lblFormat.Size = new Size(625, 30);
        lblFormat.TabIndex = 9;
        lblFormat.Text = "Nhập tiền: 1200000 hoặc 1200000,50; không dùng dấu phân nhóm.";
        lblFormat.AutoSize = false;
        lblFormat.TextAlign = ContentAlignment.MiddleLeft;
        buttonAdd.Name = "buttonAdd";
        buttonAdd.Location = new Point(280, 300);
        buttonAdd.Size = new Size(145, 36);
        buttonAdd.TabIndex = 10;
        buttonAdd.Text = "Thêm";
        buttonAdd.UseVisualStyleBackColor = true;
        buttonSave.Name = "buttonSave";
        buttonSave.Location = new Point(440, 300);
        buttonSave.Size = new Size(145, 36);
        buttonSave.TabIndex = 11;
        buttonSave.Text = "Lưu";
        buttonSave.UseVisualStyleBackColor = true;
        buttonDelete.Name = "buttonDelete";
        buttonDelete.Location = new Point(600, 300);
        buttonDelete.Size = new Size(145, 36);
        buttonDelete.TabIndex = 12;
        buttonDelete.Text = "Xóa";
        buttonDelete.UseVisualStyleBackColor = true;
        buttonExit.Name = "buttonExit";
        buttonExit.Location = new Point(760, 300);
        buttonExit.Size = new Size(145, 36);
        buttonExit.TabIndex = 13;
        buttonExit.Text = "Thoát";
        buttonExit.UseVisualStyleBackColor = true;
        listViewAccounts.Name = "listViewAccounts";
        listViewAccounts.Location = new Point(20, 355);
        listViewAccounts.Size = new Size(900, 200);
        listViewAccounts.TabIndex = 14;
        listViewAccounts.View = View.Details;
        listViewAccounts.FullRowSelect = true;
        listViewAccounts.GridLines = true;
        listViewAccounts.MultiSelect = false;
        listViewAccounts.HideSelection = false;
        listViewAccounts.Columns.Add(new ColumnHeader { Name = "col0", Text = "STT", Width = 55 });
        listViewAccounts.Columns.Add(new ColumnHeader { Name = "col1", Text = "Số tài khoản", Width = 170 });
        listViewAccounts.Columns.Add(new ColumnHeader { Name = "col2", Text = "Tên khách hàng", Width = 230 });
        listViewAccounts.Columns.Add(new ColumnHeader { Name = "col3", Text = "Địa chỉ", Width = 230 });
        listViewAccounts.Columns.Add(new ColumnHeader { Name = "col4", Text = "Số tiền", Width = 190 });
        lblTotal.Name = "lblTotal";
        lblTotal.Location = new Point(575, 580);
        lblTotal.Size = new Size(100, 28);
        lblTotal.TabIndex = 15;
        lblTotal.Text = "Tổng tiền";
        lblTotal.AutoSize = false;
        lblTotal.TextAlign = ContentAlignment.MiddleLeft;
        textBoxTotal.Name = "textBoxTotal";
        textBoxTotal.Location = new Point(680, 578);
        textBoxTotal.Size = new Size(240, 28);
        textBoxTotal.TabIndex = 16;
        textBoxTotal.ReadOnly = true;
        textBoxTotal.TextAlign = HorizontalAlignment.Right;
        buttonSave.Enabled = false;
        buttonDelete.Enabled = false;
        Controls.Add(textBoxTotal);
        Controls.Add(lblTotal);
        Controls.Add(listViewAccounts);
        Controls.Add(buttonExit);
        Controls.Add(buttonDelete);
        Controls.Add(buttonSave);
        Controls.Add(buttonAdd);
        Controls.Add(lblFormat);
        Controls.Add(textBoxAmount);
        Controls.Add(lblAmount);
        Controls.Add(textBoxAddress);
        Controls.Add(lblAddress);
        Controls.Add(textBoxCustomer);
        Controls.Add(lblCustomer);
        Controls.Add(textBoxAccount);
        Controls.Add(lblAccount);
        Controls.Add(lblTitle);
        ClientSize = new Size(940, 640);
        AutoScaleDimensions = new SizeF(96F, 96F);
        Name = "fmTaiKhoan";
        Text = "TH5D - Tại lớp 2 - Thông tin tài khoản";
        StartPosition = FormStartPosition.CenterParent;
        FormBorderStyle = FormBorderStyle.FixedDialog;
        MaximizeBox = false;
        ResumeLayout(false);
        PerformLayout();
    }

    private Label lblTitle = null!;
    private Label lblAccount = null!;
    private TextBox textBoxAccount = null!;
    private Label lblCustomer = null!;
    private TextBox textBoxCustomer = null!;
    private Label lblAddress = null!;
    private TextBox textBoxAddress = null!;
    private Label lblAmount = null!;
    private TextBox textBoxAmount = null!;
    private Label lblFormat = null!;
    private Button buttonAdd = null!;
    private Button buttonSave = null!;
    private Button buttonDelete = null!;
    private Button buttonExit = null!;
    private ListView listViewAccounts = null!;
    private Label lblTotal = null!;
    private TextBox textBoxTotal = null!;
}
