<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.1.1" />
    <ProjectReference Include="../TH5C/TH5C.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="database.config.json" CopyToOutputDirectory="PreserveNewest" />
    <None Update="Database/QLSinhVien.sql" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="fmHoSoSinhVien.cs"><SubType>Form</SubType></Compile>
    <Compile Update="fmTaiKhoan.cs"><SubType>Form</SubType></Compile>
    <Compile Update="fmChuyenLop.cs"><SubType>Form</SubType></Compile>
    <Compile Update="fmNhapHocVien.cs"><SubType>Form</SubType></Compile>
    <Compile Update="fmDemNguoc.cs"><SubType>Form</SubType></Compile>
    <Compile Update="fmMonHoc.cs"><SubType>Form</SubType></Compile>
    <Compile Update="fmSinhVienSql.cs"><SubType>Form</SubType></Compile>
    <Compile Update="fmDiem.cs"><SubType>Form</SubType></Compile>
    <Compile Update="fmLop.cs"><SubType>Form</SubType></Compile>
    <Compile Update="fmMain.cs"><SubType>Form</SubType></Compile>
  </ItemGroup>
</Project>
